dev tun
proto tcp-server
port 1194
ca ca_cert.crt
cert server_cert.crt
key server_key.key
dh none
topology subnet
server 10.8.0.0 255.255.255.0
push "topology subnet"
push "route 10.8.0.0 255.255.255.0"
keepalive 10 120
cipher AES-256-GCM
auth SHA256
tls-groups p256_mlkem512
persist-key
persist-tun
verb 3
